# Generated by Django 4.2.21 on 2025-10-24 10:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManualResmiGazeteData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_content', models.TextField(help_text='Paste the HTML content from Resmi Gazete website here', verbose_name='Resmi Gazete HTML Content')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Added')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to disable this data entry', verbose_name='Active')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this data entry', null=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Manual Resmi Gazete Data',
                'verbose_name_plural': 'Manual Resmi Gazete Data',
                'ordering': ['-date_added'],
            },
        ),
    ]
